// Auto-generated by scripts/sync-package-versions.mjs.
// Do not edit by hand. Run `pnpm sync:versions` to refresh.
export const SDK_NAME = '@hrkit/react-native';
export const SDK_VERSION = '0.1.0';
